version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db_go
    ports:
      - "5435:5432"
    volumes:
      - ./migrations/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
